---
title: "Chapter 5"
author: "Mario Zuliani"
date: "2023-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Packages
```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(meta)
library(PRISMAstatement)
library(skimr)
library(MASS)
library(ggpubr)
library(patchwork)
```
### Clean observation data
```{r}
### Load and clean up dirty data
#photo <- read.csv("observations.csv")
#photo <- photo %>%
 # filter(common_name != "Human")
#photo <- photo %>%
 # filter(common_name != "Human-Camera Trapper")
#photo <- photo %>%
 # filter(common_name != "Domestic Dog")
#photo <- photo %>%
 # filter(common_name != "Vehicle")
#photo <- photo %>%
#  dplyr::filter(common_name != "Insect")
#photo <- photo %>%
 # dplyr::filter(common_name != "Animal")
#photo <- photo %>%
#  dplyr::filter(common_name != "Bird")
#photo <- photo %>%
 # filter(common_name != "No CV Result")

#count.hit <- photo %>%
 # count(animal.hit) %>%
 # na.omit()
#summary(count.hit)


### 0.489% capture rate
```
```{r}
### Total Observations is species list!
#Total_Observations <- photo %>% group_by(common_name) %>% summarise(total = sum(animal.hit)) %>% filter(common_name != "Blank")  %>% filter(common_name != "No CV Result") %>% filter(common_name != "Mammal")

#animals_by_factor <- photo %>% group_by(factor,common_name, scientific_name) %>% summarise(captures = sum(animal.hit))
#animals_by_factor <- animals_by_factor %>% filter(common_name != "Blank")  %>% filter(common_name != "No CV Result")


#factor_obvs <- merge(animals_by_factor, Total_Observations, all = TRUE)
#factor_obvs$percent_presence <- factor_obvs$captures/factor_obvs$total
```
```{r}
### Rought version of percent proportion figure.
#write.csv(factor_obvs, file = "scientific.csv")
scientific <- read.csv("scientific.csv")
#plot1 <- ggplot(scientific, aes(scientific_name, percent_presence, fill = factor)) + geom_bar(stat = "identity") + coord_flip() + theme_classic() + scale_x_discrete(limits=rev) + xlab("Species") + ylab("Percent Proportion") + labs(fill = "factor")

#plot1 + scale_fill_manual(values = c("#009900", "#0066cc", "#8B0000")) + scale_x_discrete(limits = rev(levels(factor_obvs$scientific_name))) 
```
```{r}
### This figure works well!
library(dplyr)
library(ggplot2)

# Calculate the total counts of each species
scientific <- scientific %>%
  group_by(scientific_name, factor) %>%
  summarize(total_counts = sum(percent_presence))

# Create a custom order based on percent presence
custom_order <- scientific %>%
  arrange(factor, -total_counts) %>%
  pull(scientific_name)

# Create a numeric variable to represent the custom order
scientific <- scientific %>%
  mutate(order_var = match(scientific_name, custom_order))

# Create the bar plot with custom x-axis order
plot1 <- ggplot(scientific, aes(factor(order_var), total_counts, fill = factor)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_classic() +
  xlab("Species") +
  ylab("Relative Proportion") +
  labs(fill = "Microsite") +
  scale_fill_brewer(palette = "Paired") +
  scale_x_continuous(breaks = 1:length(custom_order), labels = custom_order) + scale_x_discrete(labels = custom_order) + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10))

plot1
```
```{r}
### Determine animal abundance at each site (This will also help with PCOA)
#photo_final <- photo  %>% filter(common_name != "Blank")  %>% filter(common_name != "No CV Result") %>% filter(common_name != "Mammal")
#write.csv(photo_final, file = "observations.csv") ### Use this as final data
photo_final <- read.csv("observations.csv")
Total_Observations_factors <- photo_final %>% group_by(site_code, factor, microsite_number) %>% summarise(total = sum(animal_hit))


```

```{r}
#animals_density <- photo %>% group_by(site_code,factor, common_name, microsite_number) %>% summarise(captures = sum(animal.hit))
#animals_density <- animals_density %>% filter(common_name != "Blank")
```


```{r}
library(dplyr)
### Geolocated Shrub Density setup and cleanup.
Cuyama_shrubs <- read.csv("Cuyama.csv")
Cuyama_shrubs <- Cuyama_shrubs %>% filter(site_code != "Cuyama_2") %>% filter(site_code != "Cuyama_4") %>% filter(site_code != "Cuyama_5") %>% filter(site_code != "Cuyama_6")

Carrizo_shrubs <- read.csv("Carrizo.csv")
Carrizo_shrubs <- Carrizo_shrubs %>% filter(site_code != "Carrizo_1")%>% filter(site_code != "Carrizo_2")%>% filter(site_code != "Carrizo_3")%>% filter(site_code != "Carrizo_4")%>% filter(site_code != "Carrizo_5")%>% filter(site_code != "Carrizo_6")%>% filter(site_code != "Carrizo_7")

shrubs <- rbind(Carrizo_shrubs, Cuyama_shrubs)
```

```{r}
### Combine site level data with geolocated data to determine the shrub density around each mimic, shrub and open area. Use Lizard code!!!
library(tidyverse)
library(sf)
library(RColorBrewer)
library(scales)
#set key attributes####
x = 4326 #crs for first spatial df
y = 4326 #crs for second spatial df
z = 20 #set buffer is using a join to point data SET FOR 20M

shrubs <- shrubs %>% 
  st_as_sf(coords=c("long","lat"), crs = x, remove=FALSE) %>% 
  st_transform(32610) #crs = 32610 is UTM and will return distances in meters

site <- read_csv("Chpt5_Site_Data.csv") %>% 
  st_as_sf(coords=c("long","lat"), crs = y, remove=FALSE) %>% 
  st_transform(32610) #crs = 32610 is UTM and will return distances in meters

buffer <- st_buffer(site, z) #decide on spatial scale
joined.xy <- st_intersection(buffer, shrubs)

joined.xy <- joined.xy %>% 
  group_by(rep) %>% 
  summarize(n_shrubs = n()) %>% 
  st_drop_geometry

tidy_all <- left_join(site, joined.xy, by = "rep") %>% 
  dplyr::mutate(n_shrubs = replace_na(n_shrubs, 0))

max(tidy_all$n_shrubs) #checks ecological viability
min(tidy_all$n_shrubs) #checks ecological viability
sum(tidy_all$n_shrubs) #checks positive co-occurrences
nrow(buffer) - nrow(tidy_all) #ensure that tidy dataframe comprised all buffers

#write data AS tidy_20m
#write.csv(tidy_all, file = "tidy_20m.csv")
library(dplyr)
tidy_20m <- read.csv("tidy_20m.csv")%>%
  distinct(rep, .keep_all = TRUE)
###write.csv(tidy_20m, file = "tidy_20m.csv")
###THIS SHOULD BE ALL CLEANED UP AND NOW WORK!!!
```
```{r}
### PCOA
library(vegan)
library(ape)

animals_density_final <- photo_final %>% group_by(site_code,factor,microsite_number, common_name) %>% summarise(captures = sum(animal_hit))

pca_data_final <- animals_density_final ### Created new df for pca data
pca_data_final <- pca_data_final %>%
  spread(common_name, captures) %>%
  ungroup() %>%
  dplyr::select(-site_code, -factor, -microsite_number) %>%
  replace(is.na(.),0)
dim(pca_data_final)

env_final <- read.csv("environment.csv") ### Drop Tecopa open 1, Tecopa open 4, since they have no animal observations.
dim(env_final)

model010 <- adonis(pca_data_final ~ factor+shrub_density, data = env_final)
model010

dist_final <- vegdist(pca_data_final, species = "bray")
res_final <- pcoa(dist_final)
p02 <- as.data.frame(res_final$vectors)%>%
  dplyr::select(Axis.1, Axis.2) %>%
  bind_cols(env_final,.)

pcoa_final <- ggplot(p02, aes(Axis.1, Axis.2, group = factor)) +
  geom_point(aes(color = factor)) +
  geom_text(aes(label=site.number), hjust = 0, vjust = 0, check_overlap = TRUE, nudge_x = 0.01)+
  scale_color_brewer(palette = "Paired") + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) + 
  labs(color = "Microsite") + theme(aspect.ratio = 1)

pcoa_final

model020 <- betadisper(dist_final, env_final$factor)
model020
anova(model020)
permutest(model020,pairwise = TRUE, permutations = 99)
model020.HSD <- TukeyHSD(model020)
model020.HSD
boxplot(model020)
```
```{r}
### Clean up and add abundance to df
library(stringr)
photo <- read.csv("observations.csv")
colnames(tidy_20m)[4] <- "microsite_number"
tidy_20m <- tidy_20m %>%
  mutate(factor = str_to_title(factor))
df <- merge(Total_Observations_factors, tidy_20m, by = c("site_code", "factor", "microsite_number"))

colnames(df)[4] <- "abundance"
colnames(df)[5] <- "rep"
colnames(df)[10] <- "shrub_density"

df <- df %>%
  dplyr::select(-functioned)
df <- df %>%
  dplyr::select(rep, everything())
df <- df %>%
  dplyr::select(-abundance, everything())
```

```{r}
### Calculate Richness across the tested sites
density_simple_2023 <- animals_density_final %>%
  group_by(site_code, factor, microsite_number) %>%
  summarise(animals = sum(captures), richness = n())
richness <- density_simple_2023 %>%
  dplyr::select(-animals)

df <- merge(df, richness, by = c("site_code", "factor", "microsite_number"))

```

```{r}
### Evenness Data
evenness_results <- animals_density_final %>%
  group_by(site_code, factor, microsite_number) %>%
  summarize(evenness = diversity(captures, index = "shannon")) ### This worked 100x better than Vegan!!!

df <- merge(df, evenness_results, by = c("site_code", "factor", "microsite_number"))

#write.csv(df, file = "Dataframe.csv")
df <- read.csv("Dataframe.csv")
```

```{r}
### Handheld Temp Data
handheld_temp <- read.csv("Chapter5_Temp_Data.csv")
colnames(handheld_temp)[5] <- "microsite_number"
colnames(handheld_temp)[8] <- "ground_temp"

handheld_temp <- handheld_temp %>%
  group_by(site_code, factor, microsite_number ) %>%
  summarise(mean_ambient_temp = mean(temp), mean_rh = mean(rh), mean_ground_temp = mean(ground_temp))

handheld_temp <- handheld_temp %>%
  mutate(factor = str_to_title(factor))

df <- merge(df, handheld_temp, by = c("site_code", "factor", "microsite_number"))

colnames(df)[7] <- "pendant_ID"
colnames(df)[8] <- "shrub_density"

```

```{r}
### Pendant Temp and test if temp is significant compared across factors
library(emmeans)
pendant_temp <- read.csv("Temp_Final.csv")
pendant_temp <- pendant_temp %>%
  group_by(site_code, factor, microsite_number) %>%
  summarise(mean_pendant_temp = mean(temp))

anova_result <- aov(mean_pendant_temp ~ factor, data = pendant_temp) ### Temp is significant.
print(summary(anova_result))

emmeans_result <- emmeans(anova_result, pairwise ~ factor) ### Mimic Significantly cooler than open areas!
print(emmeans_result)
```
```{r}
### Final Data Frame
#write.csv(df, file = "tidy_mimic_experiment.csv")
```


### Stats and Data Viz
```{r}
### use df as final dataframe since it has all required data.
### First check if temp sig varies based off handheld logger.
df <- read.csv("tidy_mimic_2023.csv")
supp1.1 <- ggplot(df, aes(x = microsite, y = mean_ambient_temp, color = microsite)) +
  geom_boxplot() + stat_summary(fun = mean, geom = "point", shape = 17, size = 2, position = position_dodge(width = 0.75 )) +
  labs(
       x = "Microsite",
       y = "Ambient Temperature (°C)") + theme_classic() + labs(tag = "A", x = NULL) +
  scale_color_brewer(palette = "Paired") + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) + theme(legend.position = "none") + theme(aspect.ratio = 1)

supp1.1

ambient_anova_result <- aov(mean_ambient_temp ~ microsite, data = df) ### Temp from handheld not significant
print(summary(ambient_anova_result))

### Check Ground temp
supp1.2 <- ggplot(df, aes(x = microsite, y = mean_ground_temp, color = microsite)) +
  geom_boxplot() + stat_summary(fun = mean, geom = "point", shape = 17, size = 2, position = position_dodge(width = 0.75 )) + labs(
       x = "Microsite",
       y = "Ground Temperature (°C)") + theme_classic() + labs(tag = "B") +
  scale_color_brewer(palette = "Paired") + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) + theme(legend.position = "none") + theme(aspect.ratio = 1)

supp1.2

ground_anova_result <- aov(mean_ground_temp ~ microsite, data = df) ### Ground temp significantly varied
print(summary(ground_anova_result))

ground_emmeans_result <- emmeans(ground_anova_result, pairwise ~ microsite) 
print(ground_emmeans_result)

### Now Humidity
ggplot(df, aes(x = microsite, y = mean_rh)) +
  geom_boxplot() +
  labs(
       x = "Factor",
       y = "Relative Humidity") + theme_classic()

rh_anova_result <- aov(mean_rh ~ microsite, data = df) ### Ground temp significantly varied
print(summary(rh_anova_result))

Supp1 <- (supp1.1 / supp1.2) +  plot_layout(guides = 'collect') + theme(legend.position = 'right') + labs(color = "Microsite")

print(Supp1)


### Final findings from temp data so far. Loggers indicate that mimics were cooler than open areas and not significantly different from shrubs. Handheld ambient indicate no significance. Handheld ground indicates that the temperature under shrubs is cooler than mimic and open, with no signifiacne between open and mimics. Finally RH is not signicant across any of the factors.
```


```{r}
### Now we test abundance with the factors.
# df now has factor = microsite and site_code has been edited to match regional.csv
library(AER) ### For testing overdispersion
plot2.1 <- ggplot(df, aes(x = microsite, y = abundance, color = microsite)) +
  geom_boxplot() + stat_summary(fun = mean, geom = "point", shape = 17, size = 2, position = position_dodge(width = 0.75 )) +
  labs(
       x = "Microsite",
       y = "Abundance") + theme_classic() +  labs(tag = "A", x = NULL)+ 
  scale_color_brewer(palette = "Paired") + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) + theme(aspect.ratio = 0.7) + theme(legend.position = "none") + theme(legend.text = element_text(size = 8))
plot2.1

hist(df$abundance, main = "Histogram of Response Variable") ### data is skewed.
shapiro.test(df$abundance)

model1 <- glm(abundance~microsite + mean_ambient_temp + shrub_density, family = "poisson", data = df)
model1
anova(model1, test = "Chisq")
abundance_emmeans_result <- emmeans(model1, pairwise ~ microsite)
print(abundance_emmeans_result)

dispersion_test_abundance <- dispersiontest(model1)
print(dispersion_test_abundance)
```


```{r}
### Richness Data
plot2.2 <- ggplot(df, aes(x = microsite, y = richness, color = microsite)) +
  geom_boxplot() + stat_summary(fun = mean, geom = "point", shape = 17, size = 2, position = position_dodge(width = 0.75 )) +
  labs(
       x = "Microsite",
       y = "Richness") + theme_classic() +  labs(tag = "B", x = NULL)+
  scale_color_brewer(palette = "Paired") + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) + theme(aspect.ratio = 0.7) + theme(legend.position = "none") + theme(legend.text = element_text(size = 8))
plot2.2

hist(df$richness, main = "Histogram of Response Variable") ### data is skewed.
shapiro.test(df$richness)


model2 <- glm(richness~microsite + mean_ambient_temp + shrub_density, family = "poisson", data = df)
model2
anova(model2, test = "Chisq")


richness_emmeans_result <- emmeans(model2, pairwise ~ microsite)
print(richness_emmeans_result)

dispersion_test_richness <- dispersiontest(model2)
print(dispersion_test_richness) ### Non sig p-value so should be good
```
```{r}
### Evenness
plot2.3 <- ggplot(df, aes(x = microsite, y = evenness, color = microsite )) +
  geom_boxplot() + stat_summary(fun = mean, geom = "point", shape = 17, size = 2, position = position_dodge(width = 0.75 )) +
  labs(
       x = "Microsite",
       y = "Evenness") + theme_classic() + labs(tag = "C") +
  scale_color_brewer(palette = "Paired") + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) + theme(aspect.ratio = 0.7) + theme(legend.position = "none") + theme(legend.text = element_text(size = 8))
plot2.3

hist(df$evenness, main = "Histogram of Response Variable") ### data is skewed.
shapiro.test(df$evenness)


model3 <- glm(evenness~microsite + mean_ambient_temp + shrub_density, family = "poisson", data = df)
model3
anova(model3, test = "Chisq")


evenness_emmeans_result <- emmeans(model3, pairwise ~ microsite)
print(evenness_emmeans_result)

dispersion_test_evenness <- dispersiontest(model3)
print(dispersion_test_evenness)


Fig2 <- (plot2.1 / plot2.2 / plot2.3) +  plot_layout(guides = 'collect') + theme(legend.position = 'right') + labs(color = "Microsite")

print(Fig2)
```
```{r}
### Abundance v Shrub Density  (Shrub density on its own is significant but not between microsites)
model7 <- glm(abundance~microsite*shrub_density, data = df) ### It is NOT poisson for this distribution! It is gaussian!
model7 ### Need to run the model this way because the figures show that microsite and temp interaction is not significant.
anova(model7, test = "Chisq")

abundance_density <- ggplot(df, aes(shrub_density, abundance, color = microsite)) +
  geom_point(size = 0.5) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "Shrub Density", y = "Abundance") + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) +
  geom_smooth(method = lm, se = TRUE) + labs(tag = "A", x = NULL) + theme(legend.position = "none") + theme(aspect.ratio = 0.8)
abundance_density
```
```{r}
### richness v density (Again, significant shrub density but not the interactio with microsite!)
model8 <- glm(richness~microsite*shrub_density, data = df) ### It is NOT poisson for this distribution! It is gaussian!
model8
anova(model8, test = "Chisq")

richness_density <- ggplot(df, aes(shrub_density, richness, color = microsite)) +
  geom_point(size = 0.5) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "Shrub Density", y = "Richness") + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) +
  geom_smooth(method = lm, se = TRUE) + labs(tag = "B", x = NULL) + theme(legend.position = "none") + theme(aspect.ratio = 0.8)
richness_density
```
```{r}
### Evenness v density (Density is not significant for evenness)
model9 <- glm(evenness~microsite*shrub_density, data = df) ### It is NOT poisson for this distribution! It is gaussian!
model9
anova(model9, test = "Chisq")

evenness_density <- ggplot(df, aes(shrub_density, evenness, color = microsite)) +
  geom_point(size = 0.5) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "Shrub Density per 20m radius", y = "Evenness") + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) +
  geom_smooth(method = lm, se = TRUE) + labs(tag = "C") + theme(legend.position = "none") + theme(aspect.ratio = 0.8)
evenness_density


density <- (abundance_density/richness_density/evenness_density) +  plot_layout(guides = 'collect') + theme(legend.position = 'right') + labs(color = "Microsite")

print(density)

```
```{r}
# Abundance v Ambient temp (No significance)
model4 <- glm(evenness~microsite*mean_ambient_temp + shrub_density, family = "poisson", data = df)
model4 ### Need to run the model this way because the figures show that microsite and temp interaction is not significant.
anova(model4, test = "Chisq")

abundance_ambient <- ggplot(df, aes(mean_ambient_temp, abundance, color = microsite)) +
  geom_point(size = 0.5) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "Ambient Temperature (°C)", y = "Abundance") + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) +
  geom_smooth(method = lm, se = TRUE) + labs(tag = "A") + labs(x = NULL) + theme(legend.position = "none") + theme(aspect.ratio = 0.8)
abundance_ambient

```
```{r}
### Richness v Ambient temperature

model5 <- glm(richness~microsite*mean_ambient_temp + shrub_density, family = "poisson", data = df)
model5 ### Need to run the model this way because the figures show that microsite and temp interaction is not significant.
anova(model5, test = "Chisq")
emmeans(model5, pairwise~microsite|mean_ambient_temp) ### Higher richness at mimic microsites than shrub and open sites

richness_ambient <- ggplot(df, aes(mean_ambient_temp, richness, color = microsite)) +
  geom_point(size = 0.5) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "Ambient Temperature (°C)", y = "Richness") + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) +
  geom_smooth(method = lm, se = TRUE) + labs(tag = "B", x = NULL) + theme(legend.position = "none") + theme(aspect.ratio = 0.8)
richness_ambient
```
```{r}
### Evenness v ambient temperature (No significance)
library(patchwork)
model6 <- glm(evenness~microsite*mean_ambient_temp + shrub_density, family = "poisson", data = df)
model6 ### Need to run the model this way because the figures show that microsite and temp interaction is not significant.
anova(model6, test = "Chisq")

evenness_ambient <- ggplot(df, aes(mean_ambient_temp, evenness, color = microsite)) +
  geom_point(size = 0.5) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "Ambient Temperature (°C)", y = "Evenness") + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) +
  geom_smooth(method = lm, se = TRUE) + labs(tag = "C") + theme(aspect.ratio = 0.8)
evenness_ambient

ambient <- (abundance_ambient / richness_ambient / evenness_ambient) +
  plot_layout(guides = 'collect') + 
  theme(legend.position = 'right') + labs(color = "Microsite")

print(ambient)

```
```{r}
### Abundance v ground temp (Need second opinion on this one!)
model10 <- glm(abundance~microsite*mean_ground_temp, family = poisson, data = df) ### Not poisson distribution! Gaussian!
model10 
anova(model10, test = "Chisq")
emmeans(model10, pairwise~microsite|mean_ground_temp)

abundance_ground <- ggplot(df, aes(mean_ground_temp, abundance, color = microsite)) +
  geom_point(size = 0.5) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "Ground Temperature (°C)", y = "Abundance") + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5),legend.title = element_blank(), axis.text = element_text(size = 10)) +
  geom_smooth(method = lm, se = TRUE)  + labs(tag = "A", x = NULL) + theme(legend.position = "none") + theme(aspect.ratio = 0.8)
abundance_ground
```
```{r}
model11 <- glm(richness~microsite*mean_ground_temp, family = poisson, data = df) ### Not poisson distribution! Gaussian!
model11 
anova(model11, test = "Chisq")
emmeans(model11, pairwise~microsite|mean_ground_temp)

richness_ground <- ggplot(df, aes(mean_ground_temp, richness, color = microsite)) +
  geom_point(size = 0.5) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "Ground Temperature (°C)", y = "Richness") + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) +
  geom_smooth(method = lm, se = TRUE) + labs(tag = "B", x = NULL) + theme(legend.position = "none") + theme(aspect.ratio = 0.8)

richness_ground
```
```{r}
### Evenness v ground temp

model12 <- glm(evenness~microsite*mean_ground_temp, family = poisson, data = df) ### Not poisson distribution! Gaussian!
model12 
anova(model12, test = "Chisq")

evenness_ground <- ggplot(df, aes(mean_ground_temp, evenness, color = microsite)) +
  geom_point(size = 0.5) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "Ground Temperature (°C)", y = "Evenness") + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 10)) +
  geom_smooth(method = lm, se = TRUE) + labs(tag = "C") + theme(legend.position = "none") + theme(aspect.ratio = 0.8)
evenness_ground

combined_plot <- (abundance_ground / richness_ground / evenness_ground) +
 plot_layout(guides = 'collect') +
  theme(legend.position = 'right') + labs(color = "Microsite")

print(combined_plot)

```
### Maps
```{r}

library(maps)
library(ggmap)
library(ggplot2)
# Set your Google Maps API key
api_key <- "AIzaSyBWSInlcZQ9hnFVEdCcZqD94IgOl95QhIs"
register_google(key = api_key)

# Specify the bounding box for the map with names
bounding_box <- c(left = -119.4, bottom = 34, right = -119.7, top = 36)

# Option 1
my_map_1 <- get_map(location = bounding_box, maptype = "terrain", source = "google", zoom = 9)

map1 <- ggmap(my_map_1) +
  geom_point(data = site, aes(x = long, y = lat, color = "black"), size = 3, shape = 16) +
  labs(title = "Map with Data Points")
map1

# Option 2
my_map_2 <- get_map(location = bounding_box, maptype = "roadmap", source = "google", zoom = 11)

ggmap(my_map_2) +
  geom_point(data = site, aes(x = long, y = lat, color = "black"), size = 3, shape = 16) +
  labs(title = "Map with Data Points")

# Option 3
my_map_3 <- get_map(location = bounding_box, maptype = "hybrid", source = "google", zoom = 11)

ggmap(my_map_3) +
  geom_point(data = site, aes(x = long, y = lat, color = "black"), size = 3, shape = 16) +
  labs(title = "Map with Data Points")

# Option 4
my_map_4 <- get_map(location = bounding_box, maptype = "terrain", source = "google", zoom = 8)

figure_1 <- ggmap(my_map_4) +
  geom_point(data = site, aes(x = long, y = lat), color = "black", size = 3, shape = 16) +
  labs(x = "Longitude", y = "Latitude")
figure_1

my_map_5 <- get_map(location = bounding_box, maptype = "terrain", source = "google", zoom = 11)

microsite <- read.csv("Chpt5_Site_Data.csv")
figure_2 <- ggmap(my_map_5) +
  geom_point(data = microsite, aes(x = long, y = lat), size = 3, shape = 16) + scale_colour_brewer(palette = "Paired")+
  labs(x = "Longitude", y = "Latitude")
figure_2
```
